#!/bin/bash

if ! command -v ffmpeg &>/dev/null; then
    echo "ffmpeg could not be found"
    exit
fi

if [ $# -lt 2 ]; then
    echo "Usage: cv time_range input_file [out_dir]"
    exit
fi

time_range=$1
input_file=$2

if [ ! -f "$input_file" ]; then
    echo "Input file does not exist"
    exit
fi

if [ $# -eq 3 ]; then
    out_dir=$3
else
    out_dir=$(dirname "$input_file")
fi

input_file_name=$(basename "$input_file")
input_file_extension="${input_file_name##*.}"
input_file_name="${input_file_name%.*}"
output_file_name="$input_file_name"_"${time_range//:/_}"."$input_file_extension"
output_file="$out_dir/$output_file_name"

# -avoid_negative_ts 1
ffmpeg -ss "${time_range%-*}" -to "${time_range#*-}" -accurate_seek -i "$input_file" -c copy "$output_file"

echo "Output file saved as $output_file"
