#!/bin/bash

if ! command -v ffmpeg &>/dev/null; then
    echo -e "\033[31mffmpeg could not be found\033[0m"
    exit
fi

if [ $# -lt 2 ]; then
    echo "Usage: cv time_range1,time_range2,... input_file [out_dir]"
    exit
fi

IFS=',' read -ra time_ranges <<<"$1"
input_file=$2

if [ ! -f "$input_file" ]; then
    echo "Input file does not exist"
    exit
fi

if [ $# -eq 3 ]; then
    out_dir="$3"
else
    out_dir=$(dirname -- "$input_file")
fi

input_file_name=$(basename -- "$input_file")
input_file_extension="${input_file_name##*.}"
input_file_name="${input_file_name%.*}"

for time_range in "${time_ranges[@]}"; do

    time_range=${time_range//./:}

    output_file_name="$input_file_name"__"${time_range//:/_}"."$input_file_extension"
    output_file="$out_dir/$output_file_name"

    echo "Processing $time_range..."

    # -avoid_negative_ts 1
    ffmpeg -loglevel error -ss "${time_range%-*}" -to "${time_range#*-}" -accurate_seek -i "$input_file" -c copy "$output_file"

    if [ $? -eq 0 ]; then
        echo -e "\033[32mOutput file saved as $output_file\033[0m"
    else
        echo -e "\033[31mFailed!\033[0m"
    fi

done
